CI2M: cy.yml creates two machines, tests/helpers/global_data.py is updated
Code was copied from testgres.os_ops package.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,6 +34,10 @@ jobs:
         echo "RUN_CFG__NOW=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV
         echo "RUN_CFG__LOGS_DIR=logs-${{ env.BASE_SIGN }}" >> $GITHUB_ENV
         echo "RUN_CFG__DOCKER_IMAGE_NAME=tests-${{ env.BASE_SIGN }}" >> $GITHUB_ENV
+        echo "RUN_CFG__NETWORK_NAME=network-${{ env.BASE_SIGN }}" >> $GITHUB_ENV
+        echo "RUN_CFG__MACHINE1_NAME=machine1-${{ env.BASE_SIGN }}" >> $GITHUB_ENV
+        echo "RUN_CFG__MACHINE2_NAME=machine2-${{ env.BASE_SIGN }}" >> $GITHUB_ENV
+        echo "RUN_CFG__SSH_KEY_NAME=id_ed25519-${{ env.BASE_SIGN }}" >> $GITHUB_ENV
         echo "---------- [$GITHUB_ENV]"
         cat $GITHUB_ENV
     - name: Checkout
@@ -42,10 +46,79 @@ jobs:
       run: mkdir -p "${{ env.RUN_CFG__LOGS_DIR }}"
     - name: Adjust logs folder permission
       run: chmod -R 777 "${{ env.RUN_CFG__LOGS_DIR }}"
-    - name: Build local image ${{ matrix.alpine }}
+    - name: Build local image
       run: docker build --build-arg PG_VERSION="${{ matrix.postgres }}" --build-arg PYTHON_VERSION="${{ matrix.python }}" -t "${{ env.RUN_CFG__DOCKER_IMAGE_NAME }}" -f Dockerfile--${{ matrix.platform }}.tmpl .
-    - name: Run
-      run: docker run $(bash <(curl -s https://codecov.io/env)) -t -v ${{ github.workspace }}/${{ env.RUN_CFG__LOGS_DIR }}:/home/test/testgres/logs "${{ env.RUN_CFG__DOCKER_IMAGE_NAME }}"
+    - name: Generate temporary SSH Key pair for CI
+      run: |
+        # Generate a key without a password directly on the GitHub Actions host
+        ssh-keygen -q -t ed25519 -N "" -f ${{ github.workspace }}/${{ env.RUN_CFG__SSH_KEY_NAME }}
+
+    - name: Setup network
+      run: |
+        docker network create ${{ env.RUN_CFG__NETWORK_NAME }}
+
+    - name: Run machine2 (for remote operations)
+      run: |
+        #
+        # "- sleep infinity" is a right command. Docker ignores "-" and runs "sleep infinity".
+        #
+        docker run -d -t \
+          --network ${{ env.RUN_CFG__NETWORK_NAME }} \
+          --name ${{ env.RUN_CFG__MACHINE2_NAME }} \
+          "${{ env.RUN_CFG__DOCKER_IMAGE_NAME }}" \
+          sleep infinity
+
+        echo "Waiting for container ${{ env.RUN_CFG__MACHINE2_NAME }} to start ..."
+        
+        # Set the timeout using the attempt counter
+        MAX_ATTEMPTS=50
+        ATTEMPT=0
+        
+        until [ "$(docker container inspect --format '{{.State.Running}}' "${{ env.RUN_CFG__MACHINE2_NAME }}")" = "true" ]; do
+          ATTEMPT=$((ATTEMPT + 1))
+          if [ $ATTEMPT -ge $MAX_ATTEMPTS ]; then
+            echo "Error: Container did not start within the allotted time (timeout)!"
+            exit 1
+          fi
+          sleep 0.2
+        done
+        
+        echo "Container successfully launched in $((ATTEMPT * 2 / 10)) second(s)!"
+
+        #
+        # Setup authorized_keys
+        #
+        cat ${{ github.workspace }}/${{ env.RUN_CFG__SSH_KEY_NAME }}.pub | \
+        docker exec -i -u test ${{ env.RUN_CFG__MACHINE2_NAME }} sh -c " \
+          cat >> /home/test/.ssh/authorized_keys && \
+          chmod 600 /home/test/.ssh/authorized_keys \
+        "
+
+        #
+        # Log status
+        #
+        docker exec -u root ${{ env.RUN_CFG__MACHINE2_NAME }} sh -c "
+          echo '--- INSIDE CONTAINER OS ---' && \
+          cat /etc/os-release && \
+          echo '--- INSIDE CONTAINER .SSH ---' && \
+          ls -la /home/test/.ssh/ \
+        "
+
+    - name: Run machine1 (main test container)
+      run: |
+        # Launch the main container, passing the private key to the .ssh folder of the test user.
+        # Pass environment variables so Python tests know where to start.
+        # Added the --rm flag so that the container is automatically deleted after the tests are completed
+        docker run --rm -t \
+          --network ${{ env.RUN_CFG__NETWORK_NAME }} \
+          --name ${{ env.RUN_CFG__MACHINE1_NAME }} \
+          -v ${{ github.workspace }}/${{ env.RUN_CFG__LOGS_DIR }}:/home/test/testgres/logs \
+          -v ${{ github.workspace }}/${{ env.RUN_CFG__SSH_KEY_NAME }}:/home/test/testgres/id_ed25519_test:ro \
+          -e TEST_CFG__REMOTE_HOST="${{ env.RUN_CFG__MACHINE2_NAME }}" \
+          -e TEST_CFG__REMOTE_PORT="22" \
+          -e TEST_CFG__REMOTE_USERNAME="test" \
+          -e TEST_CFG__REMOTE_SSH_KEY="/home/test/testgres/id_ed25519_test" \
+          "${{ env.RUN_CFG__DOCKER_IMAGE_NAME }}"
     - name: Upload Logs
       uses: actions/upload-artifact@v7
       if: always() # IT IS IMPORTANT!
